# Generated by Django 5.0.6 on 2024-07-10 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_note_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NoteQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.note')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.questiontype')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='question_types',
            field=models.ManyToManyField(through='myapp.NoteQuestionType', to='myapp.questiontype'),
        ),
    ]
