# Generated by Django 5.0.6 on 2024-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_searchresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresults',
            name='url',
            field=models.URLField(max_length=2048),
        ),
    ]
